# Generated by Django 4.2.2 on 2023-06-28 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rock_paper_scissors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesession',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_sessions_as_creator', to='rock_paper_scissors.player'),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='opponent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_sessions_as_opponent', to='rock_paper_scissors.player'),
        ),
    ]
